### ISSUE TITLE
Default behavior of merge w.r.t. equi_join selection

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#109]
I have one large array `GENEXP` (with the data of interest), and another array `GENE_KEY` which I plan to use as a selector array.

My intent is to retain the dimensionality of the `GENEXP` array after the join. 

Here is my script:

``` R
str(GENEXP)
str(GENE_KEY)

selected_genexp = merge(GENEXP, GENE_KEY, equi_join = FALSE)
selected_genexp2 = merge(GENEXP, GENE_KEY)

selected_genexp@name
selected_genexp2@name

t1 = proc.time()
temp = scidbeval(selected_genexp, temp=TRUE)
print(proc.time()-t1);

t1 = proc.time()
temp2 = scidbeval(selected_genexp2, temp=TRUE)
print(proc.time()-t1);
```

And here is the output:

``` R
> str(GENEXP)
SciDB expression  CHANDRA_GENEXP
SciDB schema  <expr:double> [gene_id=0:*,33554432,0,sample_id=0:*,128,0] 
   variable dimension   type nullable start end    chunk
1   gene_id      TRUE  int64    FALSE     0   * 33554432
2 sample_id      TRUE  int64    FALSE     0   *      128
3      expr     FALSE double     TRUE                   
> str(GENE_KEY)
SciDB expression  R_array1620319f40de1471637707391166...
SciDB schema  <study_gene_id:int64> [gene_id=0:*,33554432,0,sample_id=0:*,128,0] 
       variable dimension  type nullable start end    chunk
1       gene_id      TRUE int64    FALSE     0   * 33554432
2     sample_id      TRUE int64    FALSE     0   *      128
3 study_gene_id     FALSE int64     TRUE                   
> 
> selected_genexp = merge(GENEXP, GENE_KEY, equi_join = FALSE)
> selected_genexp2 = merge(GENEXP, GENE_KEY)
> 
> selected_genexp@name
[1] "join(CHANDRA_GENEXP, cast(R_array1620319f40de1471637707391166038,<study_gene_id:int64 NULL>[gene_id=0:*,33554432,0,sample_id=0:*,128,0]))"
> selected_genexp2@name
[1] "equi_join(CHANDRA_GENEXP, R_array1620319f40de1471637707391166038, 'left_names=gene_id,sample_id', 'right_names=gene_id,sample_id', 'left_outer=0', 'right_outer=0')"
> 
> t1 = proc.time()
> temp = scidbeval(selected_genexp, temp=TRUE)
> print(proc.time()-t1);
   user  system elapsed 
  0.016   0.004   1.851 
> 
> t1 = proc.time()
> temp2 = scidbeval(selected_genexp2, temp=TRUE)
> print(proc.time()-t1);
   user  system elapsed 
  0.024   0.004  25.668 
> 
```

Timing wise, `join` performed better. Plus I was looking to retain the dimensionality. So maybe the default of not using `equi_join` in some cases is better in such cases.

Also some output verification:

```
count(temp)
count(temp2)

head(temp)
head(temp2)
```

```
> count(temp)
[1] 10965827
> count(temp2)
[1] 10965827
> 
> head(temp)
   gene_id sample_id expr study_gene_id
1        1         0  134             0
2        1         2  240             1
3        1         3   63             2
4        1         4  346             3
5        1         5  176             4
6        1         6  139             5
7        1         7   35             6
8        1         8  433             7
9        1         9  110             8
10       1        10   74             9
> head(temp2)
   instance_id value_no gene_id sample_id expr study_gene_id
1            0        0      90       108    7         20983
2            0        1  196743        44  227       6265312
3            0        2  388564        93   61       7089318
4            0        3   64172        55  257       4540944
5            0        4  343413        54    0       6908374
6            0        5   11309        20   54       2911657
7            0        6     427        88 4752        116451
8            0        7   29928        54  813       3521161
9            0        8   90871       117  778       5344820
10           0        9   92346       100    0       5400754

```

**Comment by bwlewis** [comment]
Thanks, this is a good catch. I consider this a bug.

The logic that picks the join case is faulty in my R code. It only catches the case when the arrays have exactly the same dimensions (in which case join is always used).  What it should do is pick join when all of the dimensions of each array are used.

I'll fix this.

**Comment by ksens** [comment]
@bwlewis 
You said:

>  What it should do is pick join when all of the dimensions of each array are used.

Actually,  in my current workflow, I would prefer that the logic be modified not just for `join`, but `cross_join` also.

In my current workflow I am joining a lot while wanting to retain the dimensionality. `merge` has been a life-saver because
- I do not have to explicitly write the AFL code (it figures out which dimensions to join by)
- `merge` also figures out that if the smaller (right) array used as a `KEY` (e.g. `GENE_KEY` in above example) has slightly different chunking than the larger (left) array, then it neatly does a redimension

But the `equi_join=FALSE` flag keeps popping up again and again. 

Of course, my workflow is skewed against `equi_join` and there might be other workflows where default behavior of `equi_join` might be preferred. 

On a different note, maybe the SciDBR flag `equi_join` might be named more meaningfully? I think that `equi_join` is a SciDB internal name, but does not really make much sense in terms of R readability. 

See as an example below -- which one is more easily understandable? (I think something like the latter is more preferable):
```
selected_samples = merge(samples_by_population, selector_guide, equi_join=FALSE)
selected_samples = merge(samples_by_population, selector_guide, retain_dimensions=TRUE)
```

**Comment by apoliakov** [comment]
Yeah it's messy. 
If you can use `join()`, you should do so and it will always win. And this should be easy to detect.

When it comes to `cross_join()` against `equi_join()`, the latter should win in most cases, particularly when dealing with more than one attribute. I thought about this a lot when writing `equi_join` and wondering how bad it would be to always get rid of the dimensionality. I arrived at the idea that in most cases you rarely want to keep the dimensions. What you get post-join is a ragged sparse matrix. Why do you say you want to retain the dimensionality? Is there a subsequent join? Or are you somehow joining the arrays such that the output won't be ragged?

The big problem with `cross_join` comes if you inadvertently or sloppily end up with `cross_join(TINY, HUGE)` - you might crash at that point. I really wanted to try to protect users from that case.

**Comment by apoliakov** [comment]
Potential repro? Looks like the same thing:

```
> left@name
[1] "between(build(<a:double>[i=0:2,1000,0,j=0:2,1000,0],double(i*j)),2,null,2,null)"
> right@name
[1] "between(build(<a:double>[i=0:2,1000,0,j=0:2,1000,0],double(2*i*j)),null,1,null,1)"
> merge(left,right)[]
Error in value[[3L]](cond) : 
  Error in SGET("/execute_query", list(id = sessionid, release = release, : HTTP error 500
UserQueryException in file: src/query/parser/Translator.cpp function: resolveParamAttributeReference line: 1526
Error id: scidb::SCIDB_SE_SYNTAX::SCIDB_LE_AMBIGUOUS_ATTRIBUTE
Error description: Query syntax error. Attribute 'a' is ambiguous.
filter(project(apply(equi_join(between(build(<a:double>[i=0:2,1000,0,j=0:2,1000,0],double(i*j)),2,null,2,null), between(build(<a:double>[i=0:2,1000,0,j=0:2,1000,0],double(2*i*j)),null,1,null,1), 'left_names=i,j', 'right_names=i,j', 'left_outer=0', 'right_outer=0'), instance_id,instance_id,value_no,value_no), instance_id,value_no, i,j,a,a),true)
```
