### ISSUE TITLE
aggregate by multiple dimensions

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#110]
I think this is more of a documentation issue because I think the functionality exists. 

I start with an array with multiple dimensions:

``` R
str(selected_genotype)
```

Output:

```
SciDB expression  R_array6e9a29b242f91471782505540749...
SciDB schema  <v:double,study_sample_id:int64> [chromosome_id=0:*,1,0,start=0:*,10000000,0,end=0:*,10000000,0,alternate_id=0:19,20,0,sample_id=0:*,100,0] 
         variable dimension   type nullable start end    chunk
1   chromosome_id      TRUE  int64    FALSE     0   *        1
2           start      TRUE  int64    FALSE     0   * 10000000
3             end      TRUE  int64    FALSE     0   * 10000000
4    alternate_id      TRUE  int64    FALSE     0  19       20
5       sample_id      TRUE  int64    FALSE     0   *      100
6               v     FALSE double     TRUE                   
7 study_sample_id     FALSE  int64     TRUE             
```

I want to run the following grouped aggregate

``` R
selected_variants_2 = scidb(
  sprintf("aggregate(%s, min(v), %s)",
          selected_genotype@name,
          paste(dimnames(VARIANT), collapse=",")
          )
  )
selected_variants_2@name
```

Output:

```
[1] "aggregate(R_array6e9a29b242f91471782505540749932, min(v), chromosome_id,start,end,alternate_id)"
```

Cannot seem to get it done by the ScidBR `aggregate` function. Could not find the documentation for this in the aggregation examples at https://paradigm4.github.io/SciDBR/. Would be good to have.

**Comment by bwlewis** [comment]
Is this what you want? It's pretty clearly documented...

```{r}
iquery("create array cazart  <v:double,study_sample_id:int64> [chromosome_id=0:*,1,0,start=0:*,10000000,0,end=0:*,10000000,0,alternate_id=0:19,20,0,sample_id=0:*,100,0]")
x = scidb("cazart")
aggregate(x, by=list("chromosome_id", "start", "end", "alternate_id"),  FUN="min(v)")@name                                                 
```
```
[1] "aggregate(cazart, min(v), chromosome_id,start,end,alternate_id)"
```

**Comment by ksens** [comment]
Exactly what I wanted. Thanks.

I was trying `by=c("chromosome_id", "start", "end", "alternate_id")` and that was not working.

I see now that the documentation of SciDBR's `aggregate` as available at: 
```
?scidb::`aggregate,scidb-method`
```
says:

> "optional single character string or a list of array dimension and/or attribute names to group by"

Basically I was trying to say that the examples in the [github.io page](https://paradigm4.github.io/SciDBR/), and the one at the help above does not have an example of a group by a list. Or maybe it does somewhere, and I am completely missing it. Sorry if that is the case.
