### ISSUE TITLE
subset does not like nested expressions (or parentheses in general)

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#112]
The symbolic subset is beautiful since it automatically dispatches to filter or between:

``` R
> a = scidb("build(<val:double>[x=1:10,10,0, y=1:10,10,0], random()%10)")
> subset(a, val<5)
SciDB expression  filter(build(<val:double>[x=1:10,10...
SciDB schema  <val:double> [x=1:10,10,0,y=1:10,10,0] 
  variable dimension   type nullable start end chunk
1        x      TRUE  int64    FALSE     1  10    10
2        y      TRUE  int64    FALSE     1  10    10
3      val     FALSE double     TRUE             
```

However, as soon as we introduce a set of parentheses into the expression, there's some kind of a problem:

``` R
> subset(a, (val<5))
Error in test[!grepl("condition", lapply(test, class))] : 
  object of type 'builtin' is not subsettable
```

This means we can't make nested boolean expressions:

``` R
> subset(a, val<5 && (i == 1 || i == 3) )
Error in test[!grepl("condition", lapply(test, class))] : 
  object of type 'builtin' is not subsettable
```

That's unfortunate because it forces the user to switch between "quoted" and "non-quoted" subset forms. But the "quoted" form does not generate betweens. So it's hard to describe quite where to use which.

**Comment by bwlewis** [comment]
This can't be easily avoided. R is evaluating the stuff in the
parentheses to either TRUE or FALSE, which is the built-in value that
the complaint is about.

I don't see an easy way to support parentheses.

In fact, I think the whole non-standard evaluation thing is somewhat
of a bad idea. I'm starting to really sour on it. Maybe we should
remove?

**Comment by bwlewis** [comment]
A cheesy hack might be to replace them in the expression with some
special non-syntactical symbol like a crazy variable name, walk the
AST, and then at the end replace them back in the query string.

**Comment by apoliakov** [comment]
Ah - yeah - well it's a bummer when we have a syntax that does the between, but only some of the time. It'd be great if it worked all the time. But if it works some of the time, then we got to explain to people the whole thing from the beginning, and it kind of defeats itself... :/

I think it might be better to draw a line: either
1) the parentheses work somehow such that the subset() function can be used all the time, or
2) just expose "filter()/subset()" and "between()/[]" as first-class elements that do different things; avoid the confusion.

You know what I mean? Make sense?

**Comment by bwlewis** [comment]
NSE will never be ideal, there are warnings against its use in R's own
help. but for whatever reason, people live it (most of dplyr works like
this)

1) is hard, probably no do-able for all ir even many cases
2) really means getting rid of subset and defining filter and between
functions that don't do any parsing--just wrappers to the afl ones.

i think both suck for users...its a question of least bad option.
