### ISSUE TITLE
as.scidb for R array

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#113]
The `as.scidb` code gives an error when trying to upload an array:

```R
x = array(c(1:24), dim = c(2, 3, 4))
as.scidb(x)
```

ERROR:

```
  Error in SGET("/execute_query", list(id = sessionid, release = release, : HTTP error 500
UserQueryException in file: src/query/Expression.cpp function: resolveContext line: 365
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_REF_NOT_FOUND
Error description: Query processor error. Reference '.NA' not found.
store(reshape(input(<val:int32 null>[__row=1:24,1000000,0],
'/datastore/scidb_data/0/0/shim_input_buf_MujZEe', 0, '(int32 null)'),
<val:int32 NULL>
[i=0:1,100,0,j=0:2,100,NA,k=0:3,100,NA]),R_array3acd1543b4b21474474676025045402)
```

Now, `as.scidb` does not claim to be able to upload R arrays. So maybe it just needs to exit gracefully. 

But it seems to me that the SciDB `reshape` command was actually formulated properly. It is only that the chunk overlaps are not specified correctly (note the `NA`-s in the last line). So maybe it would be easy to fix this? I do not know what is the case for sparse arrays though.

**Comment by ksens** [comment]
As far as graceful exit is concerned:

I think the errant line is:
https://github.com/Paradigm4/SciDBR/blob/master/R/internal.R#L955

```
    X = as.matrix(as.vector(aperm(X)))
```

as it changes X from class `array` to `matrix`, and thus the subsequent check is incorrectly passed:
https://github.com/Paradigm4/SciDBR/blob/master/R/internal.R#L968

```
  if(!is.matrix(X)) stop ("X must be a matrix or a vector")
```

**Comment by bwlewis** [comment]
n-d array uploads are not supported. i think this is documented.
matrix/vector/data frame only.

**Comment by ksens** [comment]
Understandable. 

Hence my first point was: It should exit gracefully right by checking class of the input. But somehow it goes forward, and does the upload step via Shim. Then fails much later.
