### ISSUE TITLE
AFL dimensions operator is quite useful -- maybe map it to a SciDBR function?

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#117]
The `dimensions` command in SciDB seems to be very useful to find the dimensional bounds of a SciDB array. I typically find this info using an `aggregate` on the dimension of interest, but the `dimensions` operator seems to fetch this very useful info much faster. 

Any reason why it is not mapped to a SciDBR operator?

Here is an example:

```
library(scidb)
scidbconnect()
# iquery("remove(temp1)") 
iquery("create array temp1 <a:double>[i=0:*,100,0, j=0:*,100,0]")
temp1 = scidb('temp1')
t1 = scidb("build(<a:double>[i=2:2,100,0,j=3:5,100,0], random())")
t1 = redimension(t1, schema(temp1))
iquery(sprintf("insert(%s, %s)", t1@name, temp1@name))

head(temp1)
iquery("project(dimensions(temp1), name, low, high)", return=TRUE)
#  No name low high
#1  0    i   2    2
#2  1    j   3    5
```

PS: On a separate note, could I have written the above example without explicitly using the AFL `create array` i.e. so that all arrays were tied to R's garbage collector?

**Comment by bwlewis** [comment]
That used to be unreliable. Is it a reliable thing now? If so, yes, we can certainly add such a function.

At the moment, the 'dimensions' function simply returns the names of the dimensions of a 'scidb' object. The `scidb_coordinate_bounds` function returns the coordinate bounds. DId you know about that function?

One issue here is that the dimensions SciDB operator only works on named arrays. Most arrays in SciDBR are effectively views (un-evaluated SciDB AFL statements).

**Comment by bwlewis** [comment]
To answer your other question:

```{r}
x = scidbeval(redimension(scidb("build(<a:double>[i=2:2,100,0,j=3:5,100,0], random())"), "<a:double>[i=0:*,100,0, j=0:*,100,0]"))
iquery(sprintf("dimensions(%s)", x@name), return=TRUE)
```
