### ISSUE TITLE
RStudio "Error: reached elapsed time limit" 

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDBR#122]
Running on a 4 node 80 instance cloud cluster, Rstudio version 1.0.44, R 3.3.1

```
library(scidb)
scidbconnect()
GENE_SYNONYM=scidb("GENE_SYNONYM")
Error: reached elapsed time limit
```

This does not seem to occur when running R directly, but occurs frequently in RSudio running many different lines of code, but only code that interacts with the database. 

The link below has a conversation about others that have seen the problem:
https://www.mail-archive.com/r-devel@r-project.org/msg36217.html

**Comment by bwlewis** [comment]
This may be an RStudio bug.
