### ISSUE TITLE
consider making `scidb.unpack=TRUE` the default option

### ISSUE THREAD

**Issue by bwlewis** [Paradigm4/SciDBR#125]
Here is an example in favor of using unpack:

```{r}
library(scidb)
s = scidbconnect()
x = as.scidb(s, 1:5)
as.R(s$join(x, x))

#Error in value[[3L]](cond) : 
 # Error in SGET(db = structure(list(), class = "afl", connection = <environment>), : HTTP error 500
#UserQueryException in file: src/query/parser/Translator.cpp function: #resolveParamAttributeReference line: 1416
#Error id: scidb::SCIDB_SE_SYNTAX::SCIDB_LE_AMBIGUOUS_ATTRIBUTE
#Error description: Query syntax error. Attribute 'val' is ambiguous.
f#ilter(project(apply(join(R_array2c0027b971ca1482593065168398495,R_array2c0027b971ca148259#3065168398495), i,i), i, val,val), true)
```
But this works:
```{r}                                                                                                                  ^^^^
options(scidb.unpack=TRUE)
as.R(s$join(x, x))
#  i val val.1
#1 0   1     1
#2 1   2     2
#3 2   3     3
#4 3   4     4
#5 4   5     5
```

**Comment by apoliakov** [comment]
The error is in project() and it gets confused without aliases or cast :/

This will work:
`project(apply(join(R_array2c0027b971ca1482593065168398495, as A, R_array2c0027b971ca148259#3065168398495 as B), i, i), i, A.val, B.val)`

There's also a practice of applying `i` which is an attribute with the same name as a dimension. That might trip up some other ops.

But why is the project inserted to begin with?

**Comment by bwlewis** [comment]
this occurs only in the download to R code. It was added a year ago after a
long discussion on the slowness of unpack as a work around. The project
variation is often faster (sometimes a lot), so we changed it to that, but
I left the old unpack path in as an option.

I'm considering just going back to unpack, as it is not possible for me to
universally insert aliases as you suggest. If unpack is deemed slow, then
it should be fixed in scidb not the R package.

**Comment by bwlewis** [comment]
I think I solved it by just removing the project. Now we get:
```{r}
library(scidb)
s = scidbconnect()
x = as.scidb(s, 1:5)
as.R(s$join(x, x))
#  val val.1 i
#1   1     1 0
#2   2     2 1
#3   3     3 2
#4   4     4 3
#5   5     5 4
```

**Comment by bwlewis** [comment]
Ha ha, I remember why that project was put in there, and you can see why in the above example. It was simply to order the output so that the dimensions appear first!

**Comment by bwlewis** [comment]
If we don't care about column order then I say we leave this as is, I think this was a bug in before entered by Johnathan--that the column output was unexpectedly dimensions last.

**Comment by bwlewis** [comment]
OK, handled column permutation in R
