### ISSUE TITLE
Best way to edit doc?

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#127]
For my own stupidity - what's the best way to make a small edit to this page?
https://paradigm4.github.io/SciDBR/

It doesn't describe `as.R() ` at all. Wanted to add an example.

**Comment by bwlewis** [comment]
in the gh_pages branch

**Comment by apoliakov** [comment]
Yeah - looks like the HTML there was generated by some other tool? Did you use R to generate it first or something?

Also we have a separate set of wiki pages... Does it make sense to merge these things?

**Comment by bwlewis** [comment]
The doc is just the package vignette in HTML format. One possible way to create it is:

```{r}
setwd("scidb-package-source-dir/vignettes")
library(rmarkdown)
render("scidb.Rmd", output_format="html")
```

Then copy the `scidb.html` output document into the `gh-pages branch/index.html` location (it's in a different repository branch, so somewhat akward to automate this).

**Comment by bwlewis** [comment]
Rather than replace the wiki, I would like to update as much of is as possible to use the new syntax.

**Comment by bwlewis** [comment]
I got rid of the wiki, it was hopelessly out of date. The vignette is updated too.
