### ISSUE TITLE
R local variables are evaluated if defined

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#128]
I think this goes against what the doc says:

```R
> i = 4
> j = 6
> x <- db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i * j)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],24)
> as.R(x)
  i j  v
1 1 1 24
2 2 1 24
3 1 2 24
4 2 2 24
5 1 3 24
6 2 3 24
```
The doc promises ` in the above expression i and j are evaluated as SciDB dimension values, not R values.`

**Comment by apoliakov** [comment]
Dodnt look like `tryeval` has any effect. The doc still mentions tryeval; has it been removed?

```
> options(scidb.tryeval = FALSE)
> x <- db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],4)
> options(scidb.tryeval = TRUE)
> x <- db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],4)
```

**Comment by bwlewis** [comment]
when i get home later today I'll check all this. maybe i forgot to push a
commit.

indeed, treyeval was removed. no R eval should take place. Use the new R()
function inside afl expressions for that.

**Comment by bwlewis** [comment]
This is a bug, sorry. Will fix and make a test case.

**Comment by bwlewis** [comment]
I had mangled commits somehow, this should be corrected now. Needs more test coverage though.

**Comment by apoliakov** [comment]
Still seems a bit odd if "i" is a DB object:

```R
#These two seem as-advertized:
> i= 3
> x <- db$apply(db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i * j), z, i)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: apply(build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j),z,i)
> x <- db$apply(db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i * j), z, i<2)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: apply(build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j),z,i < 2)

#These two dont seem consistent? What's the right behavior?
> i= db$list()
AFL EXPRESSION: list()
> x <- db$apply(db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i * j), z, i)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: apply(build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j),z,list())  #<<-- SUBSTITUTED QUERY HERE
> x <- db$apply(db$build("<v:double>[i=1:2,2,0, j=1:3,1,0]", i * j), z, i<2)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j)
AFL EXPRESSION: apply(build(<v:double>[i=1:2,2,0, j=1:3,1,0],i * j),z,i < 2) #<<-- NO SUBSTITUTION
```

**Comment by bwlewis** [comment]
an excellent observation. Indeed I have it rigged now so that scidb objects
assigned to R variables are replaced. I think we need this, otherwise you
can't have nice syntax with apply, merge, etc. on those objects.

That is, if i remove detection of scidb objects bound to R variables, we're
mostly back to sprintf or ugly things like R(i@name).

advice?

**Comment by bwlewis** [comment]
maybe try to use the doxygen signature to selectively replace?

**Comment by apoliakov** [comment]
I considered doxygen and the help output. I worry about us getting it wrong sometimes. For example, merge accepts up to N arrays but the help signature doesn't show it:
```
> as.R(db$help("'merge'"))
  i                                                 help
1 0 Operator: merge\nUsage: merge(<input>, <input>, ...)
```
Maybe it's OK as long as an implicit substitution may only happen with a SciDB-R class object. Looks like your code does that...

I'll be playing with it more throughout the next day or so. Will continue thinking about it

**Comment by bwlewis** [comment]
I will address this with documentation.
