### ISSUE TITLE
Another interesting bit of confusion

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#132]
Why does this work:
```R
> a = db$build("<val:int64> [i=1:10], random()%2")
> as.R(db$apply(a, val2, val * 2))
```

But not this:
```R
> as.R(db$grouped_aggregate(a, val, count(*)))
Error: unexpected '*' in "as.R(db$grouped_aggregate(a, val, count(*"
```

Workaround needs quotes:
```R
> as.R(db$grouped_aggregate(a, val, 'count(*)'))
```

**Comment by bwlewis** [comment]
mentioned briefly in the help. I can't easily overload all the R infix
operators, of which many are used in afl  syntax.  thus, afl expressions
that contain R infix operators need to be quoted, unless the syntax happens
to be conformable
