### ISSUE TITLE
Forceful on Sort

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#133]
Tried a sort(build()) query and ran into a couple of issues.
1) Package forces me to specify an attribute to sort by. But that's not required by AFL. AFL defaults to sort by first attribute.
2) Doesn't like the default attribute-as-is spec; forces me to put the attribute name in quotes:

```
> a = db$build("<val:double>[i=1:10]", "random()%3")
> b = db$sort(a)
Error in sprintf("%s(%s)", attr(call, "name"), paste(lapply(as.list(match.call())[-1],  : 
  argument "attr" is missing, with no default
> b = db$sort(a, attr=val)
Error in sprintf("%s(%s)", attr(call, "name"), paste(lapply(as.list(match.call())[-1],  : 
  object 'val' not found
> b = db$sort(a, attr="val")
```

Compare with:
```
> iquery(db, "sort(build(<val:double>[i=1:10],random()%3))", return=TRUE)
```

**Comment by bwlewis** [comment]
again, infix, in this case the equals sign. try instead:

b = db$sort(a, val)

but on the larger point, indeed i forgot to specially deal with doxygen
optional arguments. this is bound to crop up elsewhere. i need to fix that,
probably most easily by making all the args effectively optional. a bona
fide bug.

**Comment by apoliakov** [comment]
I believe I tried
b = db$sort(a, val)
And it didn't work. Afk for a couple hours

**Comment by apoliakov** [comment]
Right - val without quotes does not work:
```R
> db = scidbconnect()
> db$sort(db$build("<val:double>[i=1:10]", "random()%3"), val)
Error in sprintf("%s(%s)", attr(call, "name"), paste(lapply(as.list(match.call())[-1],  : 
  object 'val' not found
> db$sort(db$build("<val:double>[i=1:10]", "random()%3"), "val")
SciDB expression  sort(build(<val:double>[i=1:10],ran...
SciDB schema  <val:double> [n=0:*:0:10] 
  variable dimension   type nullable start end chunk
1        n      TRUE  int64    FALSE     0   *    10
2      val     FALSE double     TRUE 
```

**Comment by bwlewis** [comment]
The val without quotes was separate from the aggressive function argument requirements, an obscure bug. Still working on relaxing the arguments
