### ISSUE TITLE
Error message not descriptive when db is not included in store

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDBR#150]
I'm not sure if anything can be done about this, but it might be nice to make this more descriptive in the future. 

I forgot to include the db in store and get the following error. 

``
db=scidbconnect()
out = db$list('arrays' )
**sim_output = store(out, gc = FALSE, temp=TRUE , eval=TRUE);**
Error in eval(expr) : argument "expr" is missing, with no default
``

**Comment by bwlewis** [comment]
hmmm. The error description is pretty accurate following ?store help page; the formal argument labled "expr" is missing.

**Comment by jrivers96** [comment]
It was from a customer that was unable to debug why his store wasn't working. 

We can close this if you'd like.
