### ISSUE TITLE
"list('namespaces')" does not work from SciDBR when using SciDB with namespaces on

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#151]
Accessing SciDB in namespaces mode via SciDBR, I see some unusual behaviour:

```R
scidbconnect(username = 'XXXX', password='XXXX', port=8083)
iquery("list('arrays')", return = TRUE)
# Returns result
```

But the following does not work OK. 

```R
iquery("list('namespaces')", return = TRUE)
Error in value[[3L]](cond) : 
  Error in SGET(resource = "/execute_query", args = structure(list(id = "58507", : HTTP error 500
SystemException in file: ./network/BaseConnection.h function: receive line: 420
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CANT_SEND_RECEIVE
Error description: Network error. Cannot send or receive network messages.
```

Wondering if this is by design, or is this a bug?

**Comment by bwlewis** [comment]
does iquery command line list('namespaces') work on the same system? the
error indicates a scidb issue maybe...

**Comment by ksens** [comment]
Yes, iquery command line `list('namespaces')` works on the same system.

I have a temporary fix by installing scidbr `devel` branch on that system. On that branch, this error does not happen. 

@apoliakov and I discussed and figured that this might be the problem:

On `master` branch, a show is run, generating a query like:

```sh
"join(show('filter(list(\'namespaces\'),true)','afl'), _explain_logical('filter(list(\'namespaces\'),true)','afl'))"
```

This query fails in both SciDBR and command line iquery.

On `devel` branch, maybe this show does not need to be done? And that is why this passes through OK. 

I think it is OK to close this as WONTFIX, since our plan is to move to `devel` anyway. Thoughts?

**Comment by bwlewis** [comment]
Right, that's it.  This is no longer run:

_explain_logical('filter(list(\'namespaces\'),true)','afl')


that must be crashing SciDB, should be filed as a SciDB bug even if
you close this as won't fix.

**Comment by ksens** [comment]
Filed https://paradigm4.atlassian.net/browse/SDB-5655.
