### ISSUE TITLE
Hide the password

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#154]
At the moment the password is passed as clear text to the scidbconnect command:
```R
DB <- scidbconnect(..., username="alex", password = "foobar")
```

We want to obfuscate that such that scripts do not need to contain a password. How about these two options:

## 1. Auth file
The file needs to be chmod 0600, simple key-value format, all that good stuff.
```R
DB <- scidbconnect(..., auth_file = "/home/.scidb_auth")
```

## 2. Interactive Prompt if Authentication Fails:
```R
> DB <- scidbconnect('localhost') #shim throws auth error. R prompts:

< Login: alex
< Password: ******

> #connected
```

@bwlewis what do you think?

**Comment by bwlewis** [comment]
what about just an environment variable, or reading an auth file (instead
of a special argument). neither of those requires a change.

**Comment by bwlewis** [comment]
interaction is very bad; least preferred option.

**Comment by ksens** [comment]
@bwlewis why is interaction bad? I thought that interactive login was the most intuitive way for the lay user? Obviously I am missing something.

**Comment by bwlewis** [comment]
We can do it, if you wish. For instance, we could use R's `readline` function. Your call. But what if scripts need to run on headless systems, etc.? Seems like a poor/less general choice compared with other alternatives.

**Comment by apoliakov** [comment]
I was thinking both 1 and 2: try the auth file, and if auth file is not found - use a prompt? Or maybe the prompting is controlled by an option?

**Comment by bwlewis** [comment]
I guess what I was suggesting is, just use what is already there?

```
echo "password" > ~/scidb_password
chmod 600 scidb_password
```
```{r}
library(scidb)
s = scidbconnect(..., password=readLines("~/scidb_password"))
```

requires nothing new, right?

**Comment by bwlewis** [comment]
For that matter, works interactively too!
```{r}
library(scidb)
s = scidbconnect(..., password=readline())
```

**Comment by bwlewis** [comment]
So do we really need something else?

**Comment by bwlewis** [comment]
We could rely on lazy evaluation and change the default password argument to something like:

```{r}
..., username, password=ifelse(missing(username), NULL, readline())
```

or something like that.

**Comment by ksens** [comment]
Tried this just now. Works fine I think. 

I added a prompt:
```R
db = scidbconnect(username="root", password=readline(prompt="password:"), port=8083)
```

**Comment by bwlewis** [comment]
although the danger of the default lazy option I show above is that  scripts can unintentionally freeze instead of error out (if a person is not there to notice the prompt, like a remote worker or something).

so I don't advocate changing anything

**Comment by ksens** [comment]
Not changing anything in the base package is probably fine for now. 

I, at least, want to demo the interactive capability at a client. I can make a one-off change there. 

One thing though, when readline is called, the password is entered in the clear. So it would need something else to mask the user input on the screen. 

Something like: 
http://stackoverflow.com/questions/5154335/reading-user-input-without-echoing

```R
get_password <- function() {
cat("Password: ")
system("stty -echo")
a <- readline()
system("stty echo")
cat("\n")
return(a)
}

a <- get_password()
# Password: 
a
# [1] "sdfs" 
```

or this UsePass package maybe? https://cran.r-project.org/web/packages/getPass/getPass.pdf

**Comment by bwlewis** [comment]
more reasons why interactivity is awful. not to mention keylogger vulnerability. that solution you show probably won't work on all platforms.

**Comment by bwlewis** [comment]
On a related, but different, topic. The SciDB authentication scheme is pretty awful; the password is stored in a variable in memory in the R session, and easily accessed. And shim expects the password in it's call, which goes over the network. Fortunately, not in clear text, but TLS encrypted.

An http-digest authentication scheme with a nonce is probably a better network approach. Or even better would be to just use a standard library like oauth or whatever.

The upshot is, security is not great in this package, nor in shim. Improvements would be a good idea.

**Comment by bwlewis** [comment]
OK, I put a getpwd() function in for your use. But I just discovered as I feared that the function's use of stty is indeed not portable. Thus it is limited to use on POSIX operating systems (that is, not on windows).  Oh well.

**Comment by apoliakov** [comment]
Cool! This will come in handy. Thanks Bryan

**Comment by apoliakov** [comment]
Looks like the getpwd() doesn't work in rstudio server - i.e. it displays the password. Can anything be done?
```R
> pass = getpwd()
Password:  
stty: standard input: Inappropriate ioctl for device
paradigm4
stty: standard input: Inappropriate ioctl for device
```

**Comment by bwlewis** [comment]
there are some packages with generic gui password entry, but I recommend
against depending on them.

does this happen with rstudio server too, or just rstudio?

this is far from my area of expertise other than i know to avoid it!

**Comment by bwlewis** [comment]
I'll look in to it...

**Comment by apoliakov** [comment]
Sorry I meant rstudio server, that's where it happened. I haven't tried rstudio client.

**Comment by ksens** [comment]
The `getpwd()` function does not fix the issue on RStudio Server. It does work on console R though. 

```R
# on Rstudio
> getpwd()
Password:  
asdfa
# user typed input is reflected on the screen

[1] "asdfa"
```

However there are some solutions posted [here](https://stackoverflow.com/a/16303909) that seem to work in RStudio server e.g.

```R
.rs.askForPassword("foo")`
# or 
rstudioapi::askForPassword("Enter your pw")
```

As @bwlewis  said, this is very OS specific. Folks like me need to use different calls in the application layer depending on the OS. 

@apoliakov you can test the above on RStudio server, and possibly close the issue.

**Comment by ksens** [comment]
Adding some more notes here. So far, the following work:

```R
# R on console
scidb::getpwd()

# RStudio server
.rs.askForPassword("foo")`
# or 
rstudioapi::askForPassword("Enter your pw")
```

Knitr (e.g. R-Markdown docs) on RStudio is another issue itself (getting interactive inputs on R Markdown documents is available in a very roundabout way ([see this](https://stackoverflow.com/questions/45888571/knitr-with-user-input)). While this works for the example code, it does not work when integrated with `scidbconnect()` -- throws 

```R
Error: inherits(db, "afl") is TRUE 
Error in unlockBinding("params", <environment>): no binding for "params"
...
```
