### ISSUE TITLE
`devel`: scidbconnect() fails when security is On

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#155]
My scidbconnect() call is like this:
```R
db = scidbconnect(username = 'root', password=pwroot, port=8083)
```

Works OK till before this specific commit https://github.com/Paradigm4/SciDBR/commit/74df060369aa72c1f1b2764205fabbecfe6a1b4b. At this commit, I get the error:
```R
db = scidbconnect(username = 'root', password=pwroot, port=8083)
# Error in curl_fetch_memory(uri, h) : 
#  Server returned nothing (no headers, no data)
```

Since the commit log was "internalized SciDB password hashing option", I tried providing the cleartext password too. But got the same error.

**Comment by bwlewis** [comment]
Which SciDB version are you using?

**Comment by bwlewis** [comment]
I think it's a documentation issue -- I'm changing the doc now. You also need to specify the protocol.

```{r}
db=scidbconnect(host="***", username="***", password="***", port=8083, protocol="https")
```

I'll also put in a switch so that if a username is specified, the protocol automatically switches to https.

**Comment by ksens** [comment]
Works OK now. You can close if you want to.
