### ISSUE TITLE
iquery mangles attribute names when schema is provided

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#158]
In a certain application, I download `op_count`-s of several arrays in one go. Here is an example with 2 arrays:

```R
iquery(db, 
    "join(
        op_count(build(<val:int32>[i=0:234,100,0], random())), 
        op_count(build(<val:int32>[i=0:1234,100,0], random()))
    )", return = T)
#  i count count_1
# 1 0   235    1235
```

Now adding the schema parameter speeds up the query (the metadata lookup is avoided). Also since I know the names of the arrays I am counting on, I want the return schema to have the same names. I tried providing the schema parameter for this:

```R
iquery(db, 
        "join(
            op_count(build(<val:int32>[i=0:234,100,0], random())), 
            op_count(build(<val:int32>[i=0:1234,100,0], random()))
        )", 
        schema = "<apples:uint64, oranges:uint64>[i=0:1,1,0]", return = T)
#   i apples X_oranges
# 1 0    235      1235
```

Note how the second attribute name is mangled. In some other cases, I also saw `X______arrayname`. Would be good if this could be fixed.

**Comment by bwlewis** [comment]
A subtle issue in the schema parser. The leading space before oranges is introducing the X_ (the default R behavior doesn't like leading spaces in data.frame column names, although this can be changed).

I need to make the parser aware that leading spaces in names must be stripped. This was never an issue when the schema only came from SciDB because it always returned a very regular format that was uniformly parsed. Allowing users to specify schema introduces more subtle parsing issues.

**Comment by apoliakov** [comment]
Hey this seems to still be an issue when there's a newline in the schema string:
```R
> iquery(DB, "apply(build(<val:double>[i=1:3], random()), x, 'abc')", return=T, schema="<val:double, x:string>[]", only_attributes=T)
        val   x
1 352582971 abc
2 177807121 abc
3 921979172 abc
> iquery(DB, "apply(build(<val:double>[i=1:3], random()), x, 'abc')", return=T, schema="<val:double,  
+        x:string>[]", only_attributes=T)
         val X________x
1 1834551176        abc
2  229924378        abc
3 1336939382        abc
```

**Comment by bwlewis** [comment]
Question: are there any places in a SciDB schema (old or new format) where the following characters have meaning:  space, tab, newline?

If not, I'll just always strip those characters in the schema processor.

**Comment by bwlewis** [comment]
Nevermind. Indeed, spaces are required in DEFAULT <value>, NOT NULL, etc.

**Comment by bwlewis** [comment]
Wait, are spaces, tabs, or newline characters allowed in attribute or dimension names?

**Comment by apoliakov** [comment]
No theyre not allowed in the name right now. But they can be anywhere in between...
