### ISSUE TITLE
Binary transfer 7x slower than text for small query?

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#159]
I keep chasing after the slowness that gives me sadface. This is weird:
```R
> t1=proc.time(); names = iquery(DB, "project(list(), name)", return=T, binary=TRUE); proc.time()-t1
   user  system elapsed 
  0.542   0.048   0.589 
> nrow(names)
[1] 7

> t1=proc.time(); names = iquery(DB, "project(list(), name)", return=T, binary=FALSE); proc.time()-t1
   user  system elapsed 
  0.056   0.033   0.088 
> nrow(names)
[1] 7
```
It adds up, makes my glorious UIs slower. I know the SciDB aio_save query for this runs in 0.042s in both cases, so looks like this is either a shim or an R thing... :/

**Comment by ksens** [comment]
Awesome find @apoliakov !

I had seen a similar pattern while writing an efficient way to check for existence of an array:
http://forum.paradigm4.com/t/efficiently-check-for-existence-of-an-array-in-scidb-using-scidb-r/1704

i.e. I found that using `binary = FALSE` was faster. Had not timed it then to see that it was a LOT faster, and that it could be generalized to all small queries.

**Comment by apoliakov** [comment]
When using RStudio, the `gc` call takes about 0.21 seconds - I guess it varies depending on how many files and plots and things you have:
```R
> t1=proc.time(); gc(); proc.time()-t1
           used  (Mb) gc trigger  (Mb)  max used   (Mb)
Ncells  1046865  56.0    3239836 173.1  25102783 1340.7
Vcells 18195569 138.9   52307576 399.1 355069010 2709.0
   user  system elapsed 
  0.205   0.000   0.205 
```

So that's at least half the disparity right there - the big fat GC call right in the middle of unpack_to_dataframe that can somehow be avoided when using text I guess:
https://github.com/Paradigm4/SciDBR/blob/devel/R/internal.R#L87

...but that's only about half of it...

**Comment by apoliakov** [comment]
Oh Hai! There's another `gc()` call at the end of the function!
https://github.com/Paradigm4/SciDBR/blob/devel/R/internal.R#L162

**Comment by apoliakov** [comment]
So removing those two `gc()` calls takes care of most of it. Looks like there's still a bit left:
```R
> t1=proc.time(); f = scidb_unpack_to_dataframe(DB, "project(list(), name)", schema="<name:string>[No=0:*]"); proc.time()-t1
   user  system elapsed 
  0.061   0.037   0.098 
> t1=proc.time(); f = iquery(DB, "project(list(), name)", schema="<name:string>[No=0:*]", binary=F); proc.time()-t1
   user  system elapsed 
  0.038   0.020   0.058 
```

**Comment by bwlewis** [comment]
This is a good observation. I'm removing those gc() calls. As the comment said, they are in there for a reason--I had experienced issues with the underlying curl package and inserted them. However, that package has been improved over time and they hopefully will no longer be necessary.
