### ISSUE TITLE
Ability to install `discontinued_master` branch but with different name

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#168]
Currently, one can install the `master` and `discontinued_master` branches of SciDBR package using `devtools`. However only one of the packages can exist at one time (because the name is identical).

It would be good to have the ability to install both the new SciDBR package (with name `scidb`) and the old package (with a new name e.g. `scidb1`) on the same machine. This would allow old scripts and Shiny apps built on old SciDBR package to run. 

Some notes:
- I spoke with @bwlewis and he said that there is no short-cut to change package name while installing from devtools or by using `R CMD INSTALL ...`.  The name change has to occur in the package configuration file and in the code where the compiled code is referenced with the name `scidb`. 
- It is unlikely that user would invoke both `scidb` and `scidb1` package in one script. However, if required, clashing functions could be referenced by package name (e.g. `scidb1::scidbconnect()`). Many functions from the old package (e.g. `merge`, `transform`) would not have a clash.

**Comment by apoliakov** [comment]
Closed since there was no movement since 2017. Reopen if you disagree.
