### ISSUE TITLE
SciDBR should not enforce HTTPS for SciDB auth

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#176]
## Issue description

In the following lines, SciDBR package enforces use of HTTPS protocol when SciDB authentication is used. 

https://github.com/Paradigm4/SciDBR/blob/master/R/internal.R#L350
```R
  if ("password" %in% names(args) || "auth" %in% names(args)) prot = "https://"
```

https://github.com/Paradigm4/SciDBR/blob/master/R/utility.R#L163
```R
    if (auth_type=="scidb")
    {
      attr(db, "connection")$protocol = "https"
# ...
    }
```

This rule should not be enforced by SciDBR, but should only be handled by Shim. Otherwise we face an issue with double configuration of the same setting.

## Real use case

In one customer installation, the customer IT admin decided to do the following:
- forward Shim port 8083 via Apache server to `https://HOSTNAME/shim/`. 
- allow unencrypted traffic on Shim port 8083 from `localhost`
- block 8083 to the world

(see diagram below). 
![shim-behind-ssl](https://user-images.githubusercontent.com/13973052/28843076-e8e0f720-76cd-11e7-89de-d18755e0016c.png)

For this custom Shim setup, user can connect from an external machine as
```R
scidbconnect(protocol='https', host='HOSTNAME/shim/', port=NULL, username=...)
# See https://github.com/Paradigm4/SciDBR/pull/175
```
The above works correctly with current SciDBR. 

However someone connecting from the SciDB server should also be able to connect as
```R
scidbconnect(protocol='http', host='localhost', port=8083, username=...)
```
In this case, the enforcement of `https` by SciDBR in the above mentioned code locations is problematic (i.e. even though user explicitly provided `http` in the `scidbconnect()` argument, the above code rejects the user argument and uses `https`).

**Comment by bwlewis** [comment]
password in clear text? not good.

**Comment by ksens** [comment]
I am just saying that if this rule is to be enforced, Shim should only enforce it. 

In the current case, both Shim and SciDBR are enforcing the same rule. @apoliakov and I think that SciDBR should not enforce HTTPS when user has specifically asked for HTTP. 

Separately, in the above described custom setup, the clear text password goes around only when connecting from within the SciDB machine. Traffic from other machines is encrypted. Is this scenario so bad i.e. should we not allow clear text SciDB authentication even within localhost?

**Comment by bwlewis** [comment]
yes i see. the redundancy does seem awkward. in defense of it, the extra
client-side check prevents the client accidentally sending a clear text
password, even if shim later rejects the request.

and yes, imo password should really never be in the clear anywhere. the
bolt-on shim scidb auth support is poorly designed (by me) and should be
100% re-thought.  The http basic auth is a bit better but ignores salt at
the moment and should be fixed too (or scrapped).

I really think shim needs to go! it's **long** past its shelf life...

**Comment by ksens** [comment]
@bwlewis 

I am getting around this particular with some changes in my application layer. So the changes in SciDBR code-base can be avoided here. And I agree, the double check, though redundant, is an extra layer of safety. 

Closing this issue. 

PS: In my opinion, Shim is going to be around for at least a while longer i.e. till we have a solid replacement, and also in legacy SciDB systems.
