### ISSUE TITLE
Ability to hold on to a SciDB / shim session

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#177]
@bwlewis 
In the current SciDB-R / shim integration, we get hold of a scidb session and release it after each query. I noticed that you have a flag for choosing when to release a session and when to hold on to it:
https://github.com/Paradigm4/SciDBR/blob/2573372d114e21808ef4f44edcb5a3780435d52e/R/internal.R#L424

Can this be made available to the end-user? Conceptually, this would be something like this:

```R
db = scidbconnect(username = ..., release = FALSE) # get a scidb session and hold on to it
x = scidb(db, 'ARRAY')                  # still using the same shim session id as before
y = as.R(db$limit(x, 5))                
rm(db)                                            # now the session would be released
```

**Comment by apoliakov** [comment]
@ksens I think there's also an auto-expiry mechanism inside shim. That session wont live forever.

@bwlewis we got rid of this because of DDOS issues but SciDB was improved since then. May want to re-test.

Both: we'll need to make significant SciDB-R and SciDB-Py changes here. Probably need a "long_sessions" branch on shim, SciDB-R and when ready SciDB-Py

**Comment by bwlewis** [comment]
shim would have to be changed to support this.

shim maps query output to shim session files, and right now assumes only
one query will have output per session. shim would need to map an active
session to an unbounded set of query ids, and coordinate output from those
queries to files or pipes on the server.

btw, this is why shim assumes scidb is localhost--it need a fast shared
file system with scidb from which to serve query output (ruling out slow
networked file systems) --- there was some question recently about this i
think...

imo better to spend time improving jdbc or embed a shim-like api in the db
itself, right?
