### ISSUE TITLE
[Long running shim session] Release session and temporary arrays gracefully

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#183]
Moving Shim issue https://github.com/Paradigm4/shim/issues/68 to this repo, as this deals with SciDBR, and not Shim. 

On Nov 8, 2017 @ksens wrote:

> Some more thoughts on automatic cleanup. 
> 
> 1.
> You mentioned we should call `scidbdisconnect(db)` on `finalize`. This would make sure that the session is automatically released if `db` object goes out of scope, and user forgets to explicitly call the `scidbdisconnect` function. Can you suggest a method to do this in R?
> 
> 2. 
> In scidbR, the `as.scidb()` class of upload functions create temporary arrays in SciDB (e.g. `R_array...`). In current `master` implementation of scidbR, the R variable that holds links to the temporary arrays stores a copy of the scidb username-password. So when the R variable goes out of scope, a new session is created, the temporary array is deleted, and scidb/shim session is closed. 
> 
> We need to do something similar in the long-running shim session case. Desired behavior would be something like this:
> 
> ```
> # When user has done
> x = as.scidb(db, iris)
> ```
> 
> R variable `x` stores the shim session ID in `x@meta$db$session`. When R variable linking to temporary array goes out of scope, the same session is used to delete the temporary array.
> 
> One must make sure that the session release happens after the temporary arrays are deleted. 
> 
> ### Corner case
> 
> Even after implementing the above, I see a potential leak. 
> 
> i. `x` stores link to temporary scidb array
> ii. `scidbdisconnect()` is called explicitly
> iii. `x` goes out of scope. It tries to delete temporary array using the session id stored in it. But that session has been released already. So it cannot delete
> 
> 

----------------------------
On Nov 8, 2017, @rvernica wrote:

> This looks like a SciDB-R issue and not a Shim issue.
> 
> 1. I was thinking of something like [this](https://stackoverflow.com/questions/25288646/is-there-a-destructor-in-r-reference-class):
>     ```R
>     myclass$methods(
>         finalize = function() {
>             message("I am finalizing this thing...")
>         }
>     )
>     ```
>    In (2) you say there is such a mechanism implemented for temporary arrays and they get deleted when out of scope. I guess I am thinking of the same mechanism but for `db`.
> 2. Instead of storing the username/password in the temporary array, store the session ID or even the `db` instance.
> 3. Re: Corner case. In the `db` instance you can store a list of all the temporary arrays. When `scidbdisconnect` is called, you first remove all the temporary arrays and then release the session.
> 
> [This](https://github.com/Paradigm4/SciDB-Py/blob/master/scidbpy/db.py#L481) is the `finalize`    function used in SciDB-Py for pruning temporary arrays. Each `Array` stores a copy of the `db` object. This is how we are able to delete the array. This won't work if the session is released independently by the `db` instance...

**Comment by ksens** [comment]
@rvernica 

Added a fix for (1) in https://github.com/Paradigm4/SciDBR/blob/ca8cddf52e29415171ccd188a32ae90d61e1e666/R/utility.R#L205. `reg.finalizer` does the trick. 

It turns out (2) was already resolved i.e. garbage collection does initiate removal of `R_arrays..` created in a session. The only hanging `R_arrays` are those that get missed by the corner case (when `scidbdisconnect()` is called before garbage collection has had a chance to  clean up the temporary arrays. 

The solution you proposed ("In the db instance you can store a list of all the temporary arrays. When `scidbdisconnect` is called, you first remove all the temporary arrays and then release the session.") might resolve this.

**Comment by bwlewis** [comment]
why not run gc()  in your scidbdisxonnect function to force garbage
collection?

**Comment by ksens** [comment]
Yup, working on this already.

**Comment by ksens** [comment]
@rvernica 

Please review my fix for this issue. Here is a test script

```R
library(scidb)
db1 = scidbconnect(username = 'root', password = 'Paradigm4', protocol = 'https', port = 8083)
df = as.data.frame(matrix(runif(10*100), 10, 100))

sdf = as.scidb(db1, df)
sdf2 = as.scidb(db1, df, name = "temp") # not a temporary array
sdf3 = as.scidb(db1, df, gc = FALSE) # not a temporary array
sdf4 = as. scidb(db1, df)

scidbdisconnect(db1)
rm(list=ls())
gc()
```

The last statement in above should trigger off two `remove()` commands. Two arrays should be retained. 

The corner cases my code tries to tackle are as follows:

1. User explicitly deletes a temporary array -- then `scidbdisconnect()` does not need to delete that array again.

```R
db1 = scidbconnect(username = 'root', password = 'Paradigm4', protocol = 'https', port = 8083)
df = as.data.frame(matrix(runif(10*100), 10, 100))
sdf = as.scidb(db1, df)
rm(sdf)
gc()
scidbdisconnect(db1) 
rm(list=ls())
gc()
```

2. User does not call `scidbdisconnect(db1)` explicitly. Everything is handled by garbage collector. Here I am not certain of the order in which objects will be deleted (`sdf` before `db1`, or vice versa) -- so I put the `remove()` command in silent `try()` statements. Maybe the garbage collectors in `scidb()` can also reference `attr(db, "connection")$temp_arrays` directly? 

```R
db1 = scidbconnect(username = 'root', password = 'Paradigm4', protocol = 'https', port = 8083)
df = as.data.frame(matrix(runif(10*100), 10, 100))
sdf = as.scidb(db1, df)
rm(list=ls())
gc()
```

PS:
1. You can put `options(scidb.debug=T)` to get some debug info about the deletions
2. I run something like the following to keep track of temporary arrays allocated by SciDBR

```sh
while true; do iquery -aq "project(list(), name)" | grep R_array | wc -l; sleep 1;  done
```

**Comment by ksens** [comment]
@rvernica 

Could you help with another bug I am finding here? On running `tests/a.R` with scidb security (i.e. using `scidbconnect(username = ...)`), I am seeing one intermittent failure. Could you see if you also find the same. 

Adding the traceback here. 

```R
Error in SGET(db, "/read_lines", list(id = sessionid, n = as.integer(n +  : 
  HTTP error 404 
20.
stop(e) at utility.R#362
19.
value[[3L]](cond) 
18.
tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
17.
tryCatchList(expr, names[-nh], parentenv, handlers[-nh]) 
16.
doTryCatch(return(expr), name, parentenv, handler) 
15.
tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), 
    names[nh], parentenv, handlers[[nh]]) 
14.
tryCatchList(expr, classes, parentenv, handlers) 
13.
tryCatch({
    if (at_least(attr(db, "connection")$scidb.version, 15.12)) {
        sessionid = scidbquery(db, query, save = "csv+:l", release = 0)
    } ... at utility.R#318
12.
iquery(db, sprintf("show('filter(%s, true)', 'afl')", escape), 
    return = TRUE, binary = FALSE) at internal.R#603
11.
lazyeval(db, name) 
10.
get("state") 
9.
gsub(".*<", "<", x@meta$schema) at schema-utils.R#133
8.
schema(x) at schema-utils.R#17
7.
.dimsplitter(x) at schema-utils.R#133
6.
schema(x, "dimensions") at utility.R#488
5.
as.R(x) at a.R#92
4.
eval(ei, envir) 
3.
eval(ei, envir) 
2.
withVisible(eval(ei, envir)) 
1.
source("~/coding/downloads/scidbr/tests/a.R") 
```

SciDBR commit: https://github.com/Paradigm4/SciDBR/commit/8611dd968d5244a696f07c15d797c446248accf2
Shim commit: https://github.com/Paradigm4/shim/commit/f2ff878dcf50260c49685d3a572a396e53728aaf

**Comment by rvernica** [comment]
Regarding garbage collection order:
* Arrays have a pointer to the `db` object
* After you `rm(db)`, `gc()` is not going to collect the `db` object if any arrays exist

Here is an example:
```R
> db = scidbconnect(username = 'root', password = 'Paradigm4', protocol = 'https', port = 8083)
[Shim session] created new session
> df = as.data.frame(matrix(runif(10*100), 10, 100))
> sdf = as.scidb(db, df)
> rm(db)
> gc()
# "sdf" is not removed
# "sdf" has a reference to "db"
# "db" is not garbage collected just yet
> rm(sdf)
> gc()
# "db" is garbage collected now
remove(R_array57852879bc441510624066894633765)
[Shim session] automatically cleaning up db session
remove(R_array57852879bc441510624066894633765)
```

**Comment by rvernica** [comment]
I can't get the `404` error that you get. But, `404` suggests that the session used was not found in Shim, which might be because the session is released [here](https://github.com/Paradigm4/SciDBR/commit/8611dd968d5244a696f07c15d797c446248accf2#diff-44128b3334a4d5a3d7c15bad5d4d970aR60)

What I get is this:
```R
check(a = nrow(x), b = nrow(as.R(x)))
Use the AFL op_count macro operator for an exact count of data rows.
 Hide Traceback
 
 Rerun with Debug
 Error: a and b are not equal:
  Mean absolute difference: Inf 
7.
stop(msg, call. = FALSE, domain = NA) 
6.
stopifnot(all.equal(a, b, check.attributes = FALSE, check.names = FALSE)) at a.R#4
5.
check(nrow(x), nrow(as.R(x))) at a.R#29
4.
eval(ei, envir) 
3.
eval(ei, envir) 
2.
withVisible(eval(ei, envir)) 
1.
source("~/proj/scidbr/tests/a.R", echo = TRUE) 
In addition: Warning message:
In df2scidb(db, x, name = name, gc = gc, ...) :
  Attribute names have been changed
```

**Comment by ksens** [comment]
To fix the `nrow()` error, please update your scidbR code to this commit:
https://github.com/Paradigm4/SciDBR/commit/c5fe0c7dfb64f193227cda945047ca117b9e8b0f

See if all tests in `tests/a.R` pass for you. 

Meanwhile I will try to find a repeatable case of the error I am seeing.
