### ISSUE TITLE
Still having precision issues

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#194]
@rvernica 

We fixed the case for a single vector but data.frames go across a different path. So there's a slight reduction in fidelity.

```R
#Single vector works
x = data.frame(a = rnorm(1000), b=rnorm(1000))
aa = as.scidb(db, x$a)
aaa = as.R(aa)
all.equal(aaa$val, x$a)
#TRUE 

#This fails
y = as.scidb(db, x)
y = as.R(y)
all(x$a == y$a)  #FALSE
mean(x$a - y$a)
```

Could you please take a look?

**Comment by apoliakov** [comment]
Hey @rvernica I think I got it
This is what I tried to say before - we need to upload floats using up to 17 significant figures. That preserves floating point fidelity.

I think we're good now. Look it over, let me know if you disagree:
https://github.com/Paradigm4/SciDBR/commit/9b86689e119dbcb1d6c29d35be5e485d14d3e49a

**Comment by rvernica** [comment]
I agree. Without a precision value, `%e` defaults to `6` digits after the decimal point.
