### ISSUE TITLE
Issue when returning empty data frames

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#195]
Suppose I have a data.frame in R. I want to run a query in SciDB and join the result to that. Suppose the query (maybe in this particular case) returns an empty array.

Somehow the result spit out by the query isn't merging properly:
```R
> a = scidb::iquery(db, "filter(build(<x:double>[i=0:0], 0), false)", return=T)
> b = data.frame(x=c(1,2,3))
> head(a)
[1] x
<0 rows> (or 0-length row.names)
> head(b)
  x
1 1
2 2
3 3
> merge(a, b)
Error in names(x) <- c(nm.by, nm.x) : 
  'names' attribute [2] must be the same length as the vector [1]
```

**Comment by apoliakov** [comment]
It appears that some other methods fail as well. The returned result, in this case, is a kind of "malformed" data frame. So this fails too:
```R
> data.table(a)
Error in setattr(value, "names", vnames) : 
  'names' attribute [2] must be the same length as the vector [1]
```

It appears it has to do with the lack of column type information:
```R
> class(a[,1])
[1] "NULL"
```

This appears to fix it:
```R
> for(i in 1:ncol(a)) class(a[,i])="numeric"
> data.table(a)
```

**Comment by apoliakov** [comment]
@rvernica - see above commit. That looks like it should work.
Would you please review and maybe add some tests for it?

**Comment by rvernica** [comment]
I think this needs to be extended a bit to handle `datetime`. Also, the class for `binary` seems to be `raw`. https://github.com/Paradigm4/SciDBR/blob/c643780470b1f7f391f6b9fd7caf7297e3618b8b/R/pkg.R#L112

**Comment by bwlewis** [comment]
@rvernica is right I think. It should probably return a typed data frame with zero rows, but the correct type in each column. Alternatively it could return NULL, but that would be inconsistent with data frames generally. For instance

```{r}
str(iris[FALSE,])
#'data.frame':   0 obs. of  5 variables:
# $ Sepal.Length: num 
# $ Sepal.Width : num 
# $ Petal.Length: num 
# $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 
```

**Comment by rvernica** [comment]
@bwlewis I see `iquery` returns `data.frame` most of the time, but `list` if an attribute is of type `binary`. Is this intentional?
```R
> class(iquery(db, "build(<x:binary>[i=0:0], null)", return = TRUE))
[1] "list"
> class(iquery(db, "build(<x:int64>[i=0:0], null)", return = TRUE))
[1] "data.frame"
```
Is this `list` produced by the `scidb_unpack_to_dataframe` function?

**Comment by bwlewis** [comment]
Yes this was intentional and it's relied on by PDQ--they extensively used binary blobs and SciDB.

Yes, the list return is from `scidb_unpack_to_dataframe` here:  https://github.com/Paradigm4/SciDBR/blob/master/R/internal.R#L134

Also, although data.frames *are* lists, it can be tricky to convert lists with binary data into data.frames in the way we want here (preserving the blobs). The default approach isn't usually what's wanted:

```{r}
list(a = serialize(pi, NULL))
##$a
 ##[1] 58 0a 00 00 00 02 00 03 05 00 00 02 03 00 00 00 00 0e 00 00 00 01 40 09 21
[26] fb 54 44 2d 18

data.frame(list(a = serialize(pi, NULL)))
##   a
##1  58
##2  0a
##3  00
##4  00
...
```
Instead, something like this weird trick needs to be used:
```{r}
data.frame(a=cbind(list(serialize(pi,NULL)))))
##                                                                                                                       a
## 1 58, 0a, 00, 00, 00, 02, 00, 03, 05, 00, 00, 02, 03, 00, 00, 00, 00, 0e, 00, 00, 00, 01, 40, 09, 21, fb, 54, 44, 2d, 18
```

We could change the package to always emit data frames using the trick above, but we'd also have to modify the PDQ code if we do.
