### ISSUE TITLE
Uploading values that are too low

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#196]
So, technically this is the lowest floating-point limit in R
```R
> .Machine$double.xmin
[1] 2.225074e-308
```

However doc says sometimes that limit can be broken:
```R
> x = data.frame(a = .Machine$double.xmin / 10000)
> x
              a
1 2.225074e-312
```

However SciDB won't take it:
```R
> scidb::as.scidb(db, x)
Error: HTTP error 406
UserException in file: src/query/ops/input/InputArray.cpp function: moveNext line: 179
Error id: scidb::SCIDB_SE_IMPORT_ERROR::SCIDB_LE_FILE_IMPORT_FAILED
Error description: Import error. Import from file '/run/shm/shim_input_buf_av763o' (instance 0) to array 'tmp_input_array' failed at line 1, column 0, offset 0, value='2.2250738585069563e-312': Cannot convert '2.2250738585069563e-312' of type 'string' into 'double' (Numerical result out of range).
```

This can hurt us when some other program outputs data to a text file, then we read the data into R then try to load it into SciDB. 

Suggested behavior: coerce such cases to 0 and throw a warning?

**Comment by apoliakov** [comment]
@bwlewis @rvernica any thoughts on this?

**Comment by rvernica** [comment]
To add to this, I think the SciDB R limit changes if you use aio_tools or not. I'll put together an example once I finish the empty data.frame issue.

**Comment by bwlewis** [comment]
Those smaller numbers are denormalized floating point numbers, they are valid and understood by most modern CPUs. There are some compiler directives that can be used to disable them, but that wouldn't help in this case cause it's R that is emitting them. They are important to use to avoid roundoff errors of small values within computtions, but in this case (data transfer) truncating them to zero is a totally valid approach in my opinion.
