### ISSUE TITLE
19.3 scidbR issue

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#203]
Running into this issue while trying to work with scidbR on scidb 19.3.

```sh
iquery(db, "limit(gh_secure.DATASET,5)", return = T)
Error: HTTP error 406UserException in file: src/array/TemplateParser.cpp function: parse line: 67
Error id: scidb::SCIDB_SE_EXECUTION::SCIDB_LE_ATTRIBUTES_MISMATCH
Error description: Error during query execution. Attributes mismatch.
Failed query id: 7.1580125949794814844
```

Package versions

```
yum list installed | grep extra-scidb
extra-scidb-libs-19.3.x86_64          3-1                        @scidb-extra
```

```
R --slave -e "packageDescription('scidb')"
# RemoteRef: master
# RemoteSha: bd0629719d45130275465e9f949b0208444e4238
```

I also get the same error when I install branch `v19.3` from 
github.com/paradigm4/scidbr

Any suggestions folks? @rvernica @wenweiP4 @apoliakov

**Comment by wenweiP4** [comment]
I did recently merge a fix PR to SciDBR package. The PR includes a bug fix of data type conversion and add compatibility for scidb v19. So far the package works fine on the bms scidb v19 server

Can you try 
```{sh}
afl: store(limit(gh_secure.DATASET, 10), tmparray)
Then:
iquery(db, "limit(tmparray,5)", return = T)
```

**Comment by ksens** [comment]
Found the issue -- wasn't related to latest PR-s on `scidbr` repo. 

The issue was that shim settings were set to `aio=0` i.e. `accelerated_io_tools` was not being used. Turning setting to `aio=1` and restarting shim solved the issue. 

Closing.
