### ISSUE TITLE
Delete v19.3 branch of scidbR

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#205]
Seems to me that with latest changes to `master` by @wenweiP4 , the [v19.3 branch](https://github.com/Paradigm4/SciDBR/tree/v19.3) is not required anymore.

I believe the main version related change is this: Keyword parameter style for `aio_input` is interpreted automatically by inferring the scidb version from connection object https://github.com/Paradigm4/SciDBR/pull/202

Thus I propose that we delete the `v19.3` branch to avoid confusion in the future. Can folks confirm? 

CC: @apoliakov

**Comment by wenweiP4** [comment]
I haven't worked on v19.3 branch. But a quick `git diff master origin/v19.3` shows that they were the same before I made the recent changes. So I don't see any problems deleting `v19.3` branch. Please correct me if I'm wrong @apoliakov

**Comment by apoliakov** [comment]
I agree with your assessment - go ahead.

**Comment by ksens** [comment]
Thanks. Deleted.
