### ISSUE TITLE
Long vectors not being uploaded via `as.scidb`

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#220]
The following passes:

```R
xx = as.scidb(con$db, sample(1:10^10, 10^8))
```

However, this fails:
```R
xx = as.scidb(con$db, sample(1:10^10, 10^9))
```

```
Error in handle_setopt(h, .list = list(ssl_verifyhost = as.integer(getOption("scidb.verifyhost",  : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:535
In addition: Warning message:
In handle_setopt(h, .list = list(ssl_verifyhost = as.integer(getOption("scidb.verifyhost",  :
  NAs introduced by coercion to integer range
```

Assigning to @arko-bhattacharya for investigation.

**Comment by apoliakov** [comment]
Hey guys! I did some looking into this.

It looks like the limit is right around 2GB. The limit seems to be the same for numerics and strings. But careful with strings! The function `object.size` doesn't actually report the full "size of uploaded payload" for `character` vectors. This is because R keeps a "global registry of unique strings" and character vectors point into it. Thus a better way is to use `nchar`. Here is an example:

```R
> a = rep('Hi there! My name is Alex. How are you doing?', 50000000)

> object.size(a)  #400MB
400000144 bytes

> sum(nchar(a)) #2.25 billion characters (which is more than 400MB)
[1] 2.25e+09

> x = scidb::as.scidb(bb$db, a)
Error in handle_setopt(h, .list = list(ssl_verifyhost = as.integer(getOption("scidb.verifyhost",  : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:522
In addition: Warning message:
In handle_setopt(h, .list = list(ssl_verifyhost = as.integer(getOption("scidb.verifyhost",  :
  NAs introduced by coercion to integer range
```

Another finding is that when the vector is MUCH bigger, you can get a straight R crash; probably an error that's triggered earlier.

**Comment by apoliakov** [comment]
Here's a quick and hacky workaround example for numerics, using scidb's `append` op for vectors. The append time is decent.

```R
upload_vector_multipart = function( v, attr_name = "val") {
  if(class(v) != 'numeric') {
    stop('only numeric supported now. Generalize me to support character, bruh!')
  }
  if(class(v) == 'numeric') {
    block_size = 50000000 #maybe bigger?
  }
  # else if class(v)=='character', use sum(nchar) to figure out block size?
  # remember we don't allow NA character uploads because they won't work
  name = scidb:::tmpnam(bb$db)
  schema = sprintf("<%s: double null> [i=0:*:0:100000]", attr_name)
  scidb:::create_temp_array(bb$db, name, schema=schema) 
  result = scidb::scidb(bb$db, name, gc=T) #make the handle that shall be garbage-collected
  total_length = length(v)
  for (start in seq(1, total_length, block_size)) {
    print(paste("Uploading part", start))
    end <- min(total_length, start + block_size - 1)
    x = scidb::as.scidb(bb$db, v[start:end])
    scidb::iquery(bb$db, sprintf("append(%s, %s)", x@name, result@name))
  }
  return(result)
}

x = sample(1:10^10, 3*10^8)
x_db = upload_vector_multipart(x)
options(scidb.result_size_limit = 10*1024)
y = as.R(x_db)
y = y[order(y$i), ]
nrow(y) == length(x)
all.equal(y$val, x)
```

**Comment by apoliakov** [comment]
We made a fix in biobank for now. It is here:
https://github.com/Paradigm4/biobank/blob/81669cba59aefe091d84a0cc8d1653ccfe96db44/pkg/R/utilities.R#L10

We're still not sure what the root cause is; worth investigating.

**Comment by arko-bhattacharya** [comment]
The above described error originates from function curl::handle_setopt. 

This function is called by the POST function in internal.R at -https://github.com/Paradigm4/SciDBR/blob/dd6a192677b3bd9514b8391a19bf0717cc20ab47/R/internal.R#L465

**Comment by ksens** [comment]
@apoliakov 

@arko-bhattacharya and I chatted about this last week:

- As pointed out above, it seems the error arises from a call to the external function `curl::handle_setopt()` (in `internal.R` at [this line in SciDBR package])(https://github.com/Paradigm4/SciDBR/blob/dd6a192677b3bd9514b8391a19bf0717cc20ab47/R/internal.R#L465). 
- We think it is **NOT** the best use of our resources to try and improve `curl::handle_setopt()` to try and accept larger uploads. Theoretically, there will always be an upper limit to the upload-at-one-go approach. 
- So our current strategy is that @arko-bhattacharya will start implementing the same approach as in biobank (automated multi-part upload, but do that for `as.scidb`)
- To test out the strategy, we will start with one data type -- vector of `numeric`-s

```R
xx = as.scidb(con$db, sample(1:10^10, 10^9))
# this fails with above mentioned curl::handle_setopt() error
```

- If the approach works smoothly for one data type, then @arko-bhattacharya will proceed with other data types in order of priority

@apoliakov Does this strategy sound good to you? We will proceed accordingly.

**Comment by apoliakov** [comment]
Yeah we can try this and see how it goes. Keep in mind there's a different code path for data.frames and vectors. We can start with vectors. Data.frames have their own, similar limitation when we convert them to text for upload.

**Comment by ksens** [comment]
@arko-bhattacharya 

Pasting the AFL code snippet we discussed for multi-part loads:

```R
# initial array: A ==> <val: double> [i]

qq  = glue::glue(
  "insert(
    redimension
      cast(
        apply(A, new_i, i + int64({start_idx})), 
        (i, old_i), (new_i, i)),                      # array ==> <val: double, i: int64> [old_i]
      {target_arr}),                                  # array ==> <val: double> [i]
    {target_arr})"
  )
iquery(db, qq)
```

**Comment by apoliakov** [comment]
Note that `append` is likely to be faster - where applicable. That's why we use `append` in the code example above. Just in case.

**Comment by arko-bhattacharya** [comment]
@ksens Apologies for a long message.

Here are my thoughts on uploading relatively 'big' data sets to SciDB via as.scidb() - 
1. as.scidb() calls -
    1. matvec2scidb() for uploading vectors (numeric and character), dense matrices and n-d arrays.df2sc
    2. df2scidb() for uploading dataframes
    3. .Matrix2scidb() for uploading sparse matrices
2. These ...2scidb() functions are structured as follows -
    1. Check input args
    2. Define upload schemas
    3. Convert data to raw bytes
    4. Load data to SciDB
3. The bottle neck for as.scidb() to load big objects to SciDB is scidb::::POST function which has a dependency on Rcurl's maximum POST size.
4. To fix this I believe we should break objects into smaller size before converting them to raw bytes. I think we should change ...2scidb() function's flow as follows -
    1. Check input argument
    2. Define a parent upload schema/s
    3. Break data into reasonable blocks. For each block -
       1. Convert data to raw bytes
       2. Load data to SciDB
I believe we can then have a single mulipart_post function which is called by all the ...2scidb() functions.
5. Reasonable size is a tricky problem as -
    1. It is still not clear to me how we can measure size of an object reliably in R. As Alex has pointed out above, for character vector's object.size() does not report the size of the object that will be uploaded. 
    2. Similar problems can exist while uploading numeric vectors with long precision, and character vectors with huge string lengths in each element. 
    3. The fix I have made is only for numeric vectors, but here too I have defined a pre-set vector length as the block length but the ideal way should be to measure the size of the vector and break it into blocks of optimal length as this will ensure we break the data into minimum chunks and load it in the least time. 
    4. Perhaps Hadley Wickham's pryr package might be able to help us to some extent to measure object size but breaking the data into optimal chunks is an interesting challenge.

**Comment by arko-bhattacharya** [comment]
The default value of `scidb.max_byte_size` is set at 500*(10^6) i.e 500MB.

The reason for doing so is -
* Let's consider a character vector of size 10^9 with each element containing a single character.
* This implies the effective block size in https://github.com/Paradigm4/biobank/blob/master/pkg/R/utilities.R#L35 is `block_size = ceiling(max_byte_size/max(c(1,nchar(v, type="bytes")), na.rm = T)` which is equivalent to `block_size = max_byte_size`.
* If `scidb.max_byte_size = 1.75GB` then `block_size = 1.75*(10^9)`.
* This implies that the entire vector will be uploaded without breaking into smaller units. 
* This will fail as we know that this is beyond RCurl's POST-ing limit.

Due to this reason the default value of 'scidb.max_byte_size' is set at 500*(10^6) i.e 500MB and can be increased per use case.
