### ISSUE TITLE
Need support for SciDB data.frame support in SciDBR

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#224]
@arko-bhattacharya 

Here is some starter documentation for SciDB data.frames (look towards the end of the article):
https://paradigm4.atlassian.net/wiki/spaces/scidb/pages/1973391456/SciDB+Database+Arrays

Also read the `flatten` operator linked at above page. 

For the first work item, could you look into the ability to download scidb dataframes using `as.R`. Maybe start by creating a scidb dataframe by using `flatten` on a regular scidb array, and then running `as.R` on that dataframe from R -- what's the error that arises in this case?

**Comment by arko-bhattacharya** [comment]
Cause of error -
* `as.R` and `iquery` internally call `scidb_unpack_to_dataframe` which internally formulates a queries dimension from its SciDB object schema.
* This internal dimension (recorded as an R data.frame) in case of a SciDB dataframe contains the value `$inst` under the column - 'name'. This causes an error as the name `$inst` is reserved by SciDB for system use.
