### ISSUE TITLE
Image function strangeness

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#67]
Given:

```R
> foo
A reference to a  9x9 SciDB array
> foo@schema
[1] "<mutated_right:double NULL DEFAULT null> [gene_id_1=1:9,100,0,gene_id_2=1:9,100,0]"
> foo[]
9 x 9 sparse Matrix of class "dgCMatrix"
  1 2 3  4 5 6 7  8   9
1 . 8 6 11 3 6 1 17 208
2 . . 6 11 3 6 1 16 208
3 . . . 12 3 6 1 16 207
4 . . .  . 3 6 1 17 207
5 . . .  . . 5 1 17 209
6 . . .  . . . 1 17 209
7 . . .  . . . . 17 209
8 . . .  . . . .  . 205
9 . . .  . . . .  .   .
```

The result of image(foo) is strangely transposed (or the axes are labeled improperly). Also obviously image(foo) and image(foo[]) do not agree.

**Comment by bwlewis** [comment]
This seems to have been fixed at some point, but see the discussion below.

R's default `image` function is no good. We should follow the Matrix package version, which is very unfortunately inconsistent with the base `image` function for historical reasons from S. Consider:

```{r}
x=matrix(rnorm(100), 10)
x[upper.tri(x)]=0

image(x)

# versus
library(Matrix)
image(Matrix(x))
```

That latter version is oriented the way people seem to expect it to be (Matlab and Python follow that orientation by default for example). Just FYI...
