### ISSUE TITLE
Problems using SciDBR with RStudio version greater than 0.99.484

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#77]
The symptom of the problem is that creating the same array reference twice will freeze RStudio:
```R
> array = scidb("DATA")
> array = scidb("DATA")
[RStudio interpreter freezes]
```

This affects only RStudio (not the regular R interpreter) and only versions above 0.99.484. We confirmed it's an RStudio issue. For now, the workaround is to use an earlier version of RStudio:
```
wget https://download2.rstudio.org/rstudio-server-0.99.484-amd64.deb
sudo gdebi rstudio-server-0.99.484-amd64.deb
```

**Comment by bwlewis** [comment]
This has been fixed in RStudio version Version 0.99.903
