### ISSUE TITLE
Low rate bulk transfers from SciDB to R

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDBR#89]
**Summary**
We are getting around 14 MB/s rates into R(laboratory version)  from SciDB. 

**Description**
We are utilizing a R3.4 xLarge Amazon EC2 instance and a config file listed at the bottom of this ticket. The data is being transferred to a flash drive and then into R. 

We are transferring **4.4 Gigabytes** of a one attribute flat array into R from SciDB. This is the in SciDB size. The data is 4.9 GB on disk in the binary packed form. 

iquery -aq "summarize(project(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),total_lmp))"
{inst,attid} att,count,bytes,chunks,min_count,avg_count,max_count,min_bytes,avg_bytes,max_bytes
{0,0} 'all',158440815,**4435689408**,304,6984,1.04237e+06,37837848,57036,1.45911e+07,908108376

**Start Query**

> scidbconnect()
> array_redim     = scidb("array_totalv11")
> array_redim_prj = project(array_redim, c('total_lmp', 'congestion_price', 'marginal_loss_price'))
> options(scidb.debug=TRUE) 
> t1 = proc.time();
> a = iquery(array_redim_prj$total_lmp, return=TRUE); dt = proc.time() - t1

join(show('filter(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),true)','afl'), _explain_logical('filter(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),true)','afl')) 
Query time 0.061 
Data transfer time 0.003 
R parsing time 0.001 
join(show('filter(project(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),total_lmp),true)','afl'), _explain_logical('filter(project(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),total_lmp),true)','afl')) 
Query time 0.062 
Data transfer time 0.002 
R parsing time 0.002 
join(show('filter(unpack(project(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),total_lmp), i),true)','afl'), _explain_logical('filter(unpack(project(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),total_lmp), i),true)','afl')) 
Query time 0.068 
Data transfer time 0.003 
R parsing time 0.001 
unpack(project(project(array_totalv11,total_lmp,congestion_price,marginal_loss_price),total_lmp), i) 

Query time 63.568 
Data transfer time 6.375 
  R buffer  3300000 / 5228546895  bytes parsing time 0.022 
  R rbind/df assembly time 0.001 
  R buffer  333300000 / 5228546895  bytes parsing time 2.208 
  R rbind/df assembly time 1.895 
  R buffer  663300000 / 5228546895  bytes parsing time 2.21 
  R rbind/df assembly time 3.744 
  R buffer  993300000 / 5228546895  bytes parsing time 2.208 
  R rbind/df assembly time 5.688 
  R buffer  1323300000 / 5228546895  bytes parsing time 2.208 
  R rbind/df assembly time 7.301 
  R buffer  1653300000 / 5228546895  bytes parsing time 2.209 
  R rbind/df assembly time 9.146 
  R buffer  1983300000 / 5228546895  bytes parsing time 2.209 
  R rbind/df assembly time 10.931 
  R buffer  2313300000 / 5228546895  bytes parsing time 2.208 
  R rbind/df assembly time 12.893 
  R buffer  2643300000 / 5228546895  bytes parsing time 2.241 
  R rbind/df assembly time 14.694 
  R buffer  2973300000 / 5228546895  bytes parsing time 2.209 
  R rbind/df assembly time 16.49 
  R buffer  3303300000 / 5228546895  bytes parsing time 2.22 
  R rbind/df assembly time 18.326 
  R buffer  3633300000 / 5228546895  bytes parsing time 2.209 
  R rbind/df assembly time 20.046 
  R buffer  3963300000 / 5228546895  bytes parsing time 2.209 
  R rbind/df assembly time 21.899 
  R buffer  4293300000 / 5228546895  bytes parsing time 2.208 
  R rbind/df assembly time 23.685 
  R buffer  4623300000 / 5228546895  bytes parsing time 2.207 
  R rbind/df assembly time 25.812 
  R buffer  4953300000 / 5228546895  bytes parsing time 2.209 
  R rbind/df assembly time 27.614 
  R buffer  5228546895 / 5228546895  bytes parsing time 1.845 
  R rbind/df assembly time 29.435 
Total R parsing time 284.643 

**This gives a total rate of for SciDB transfer to R DataFrame:**

> object.size(a) / dt[3]
> 14259778.6771592 bytes
> 
> dt[3]
> elapsed 
> 355.553 

*_It spends 80% of the time in R parsing the data. *_

> 284/355
> [1] 0.8

config.ini
[mydb]
server-0=127.0.0.1,15
security=trust
db_user=dbuser
install_root=/opt/scidb/15.12
pluginsdir=/opt/scidb/15.12/lib/scidb/plugins
logconf=/opt/scidb/15.12/share/scidb/log4cxx.properties
base-port=1239
base-path=/home/scidb/scidb_data

execution-threads=9
result-prefetch-threads=8
result-prefetch-queue-size=2
operator-threads=2

mem-array-threshold=2048
smgr-cache-size=2048
merge-sort-buffer=1024
sg-receive-queue-size=32
sg-send-queue-size=16

**Comment by bwlewis** [comment]
Not a bug? As far as I can tell maybe this is a question, or an enhancement request?

**Comment by apoliakov** [comment]
I'm seeing some similar things. Here's a very basic example: a 1.6GB array build, single attribute, the AIO save time is ~30 seconds but the R re-ingest time is like 280 seconds:

```
$ iquery -anq "store(build(<val:double> [x=1:200000000,1000000,0], random()),tmp)"
Query was executed successfully

$ iquery -aq "summarize(tmp)"
{inst,attid} att,count,bytes,chunks,min_count,avg_count,max_count,min_bytes,avg_bytes,max_bytes
{0,0} 'all',200000000,1600024000,400,1000000,1e+06,1000000,48,4.00006e+06,8000072
```

```R
scidb@ip-10-233-173-99:~$ R

R version 3.2.4 (2016-03-10) -- "Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library('scidb')
   ____    _ ___  ___
  / __/___(_) _ \/ _ )
 _\ \/ __/ / // / _  |
/___/\__/_/____/____/     Copyright 2016, Paradigm4, Inc.



Attaching package: ‘scidb’

The following objects are masked from ‘package:stats’:

    phyper, qhyper

> scidbconnect()
> options(scidb.debug=TRUE)
> t = iquery("scan(tmp)", return=TRUE);
join(show('filter(scan(tmp),true)','afl'), _explain_logical('filter(scan(tmp),true)','afl')) 
Query time 0.052 
Data transfer time 0.003 
R parsing time 0.001 
join(show('filter(unpack(scan(tmp), i),true)','afl'), _explain_logical('filter(unpack(scan(tmp), i),true)','afl')) 
Query time 0.056 
Data transfer time 0.002 
R parsing time 0.001 
unpack(scan(tmp), i) 
Query time 26.757 
Data transfer time 4.406 
  R buffer  1700000 / 3.4e+09  bytes parsing time 0.018 
  R rbind/df assembly time 0.001 
  R buffer  171700000 / 3.4e+09  bytes parsing time 1.82 
  R rbind/df assembly time 1.323 
  R buffer  341700000 / 3.4e+09  bytes parsing time 1.821 
  R rbind/df assembly time 2.589 
  R buffer  511700000 / 3.4e+09  bytes parsing time 1.843 
  R rbind/df assembly time 3.831 
  R buffer  681700000 / 3.4e+09  bytes parsing time 1.821 
  R rbind/df assembly time 4.779 
  R buffer  851700000 / 3.4e+09  bytes parsing time 1.824 
  R rbind/df assembly time 5.985 
  R buffer  1021700000 / 3.4e+09  bytes parsing time 1.828 
  R rbind/df assembly time 7.044 
  R buffer  1191700000 / 3.4e+09  bytes parsing time 1.823 
  R rbind/df assembly time 8.581 
  R buffer  1361700000 / 3.4e+09  bytes parsing time 1.82 
  R rbind/df assembly time 9.744 
  R buffer  1531700000 / 3.4e+09  bytes parsing time 1.821 
  R rbind/df assembly time 11.042 
  R buffer  1701700000 / 3.4e+09  bytes parsing time 1.82 
  R rbind/df assembly time 11.986 
  R buffer  1871700000 / 3.4e+09  bytes parsing time 1.821 
  R rbind/df assembly time 13.164 
  R buffer  2041700000 / 3.4e+09  bytes parsing time 1.82 
  R rbind/df assembly time 14.286 
  R buffer  2211700000 / 3.4e+09  bytes parsing time 1.824 
  R rbind/df assembly time 15.492 
  R buffer  2381700000 / 3.4e+09  bytes parsing time 1.822 
  R rbind/df assembly time 16.963 
  R buffer  2551700000 / 3.4e+09  bytes parsing time 1.822 
  R rbind/df assembly time 17.996 
  R buffer  2721700000 / 3.4e+09  bytes parsing time 1.821 
  R rbind/df assembly time 19.47 
  R buffer  2891700000 / 3.4e+09  bytes parsing time 1.823 
  R rbind/df assembly time 20.427 
  R buffer  3061700000 / 3.4e+09  bytes parsing time 1.83 

  R rbind/df assembly time 21.45 
  R buffer  3231700000 / 3.4e+09  bytes parsing time 1.822 
  R rbind/df assembly time 22.505 
  R buffer  3.4e+09 / 3.4e+09  bytes parsing time 1.803 
  R rbind/df assembly time 23.962 
Total R parsing time 289.096 

> packageDescription('scidb')
Package: scidb
Type: Package
Title: An R interface to SciDB
Version: 2.0.0
Date: 2015-09-07
Authors@R: c( person("B. W.", "Lewis", role=c("cre","aut"),
        email="blewis@illposed.net"), person("Alex", "Poliakov",
        role=c("aut"), email="apoliakov@paradigm4.com") )
Copyright: Paradigm4, Inc.
Description: An R interface to the SciDB array database
        (http://scidb.org).
BugReports: https://github.com/Paradigm4/SciDBR/issues
URL: http://paradigm4.github.io/SciDBR
VignetteBuilder: knitr
Depends: R (>= 3.0.0)
Imports: methods, utils, Matrix, stats, graphics, digest, codetools,
        curl
Suggests: knitr (>= 1.8)
License: AGPL-3
LazyLoad: yes
RoxygenNote: 5.0.1
Author: B. W. Lewis [cre, aut], Alex Poliakov [aut]
Maintainer: B. W. Lewis <blewis@illposed.net>
Built: R 3.2.4; x86_64-pc-linux-gnu; 2016-04-07 21:34:49 UTC; unix
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: SciDBR
RemoteUsername: paradigm4
RemoteRef: laboratory
RemoteSha: a6c134293fac768745c74f4b8f6a1854913d2c90
GithubRepo: SciDBR
GithubUsername: paradigm4
GithubRef: laboratory
GithubSHA1: a6c134293fac768745c74f4b8f6a1854913d2c90

-- File: /usr/local/lib/R/site-library/scidb/Meta/package.rds 
```

**Comment by bwlewis** [comment]
This is a feature request for faster data parsing. A few notes:

1. Since R is a column store, columnar output from SciDB would be much better!
1a. Also saving in a native format to avoid parsing on the client side would help. Right now the client parses everything in SciDB custom native nullable format. One approach to improve this might be to just not allow nullable stuff, but that feels wrong from the R perspective where everything is potentially missing (aka nullable in database vernacular).
2. Most of the timing complaint above I think is due to concatenation of data frames as we read row-wise through data.

#2 can be addressed a few ways by increasing the buffer size to reduce concatenation steps and corresponding memory allocations and copies. Or maybe use a more efficient internal representation to build the output like data table. Or both. Investigating.

**Comment by apoliakov** [comment]
It would not be hard to add a new kind of format to aio_save, but it would be easiest to make it semi-columnar:
[1 million values for column0][1 million values for column1]...[another million values for column 0]...

On the other hand, if you want
[all of column0][all of column 1]...

It's easier to do with just K queries, one per attribute. Well.... depending on if the array is pre-computed of course :/

Looks a little messy but we got some options... Let me know what you think.

**Comment by bwlewis** [comment]
Try things now. I introduced a data.table dependency (only used internally), and also increased the max buffer size.

**Comment by apoliakov** [comment]
An improvement, but there's a strange problem. Using the same "tmp" array from above, noting it is 3.2GB when binary-saved, I'm getting a transfer throughput of around 43MB/s. The problem is, that only happens the first time! Weird. The second time I do it - gets much worse. And the third time... The R process does a lot of spinning in top with a RES footprint of >10GB which is also strange - why does it need so much mem?

```R
First time:
 scidbconnect()
_setopt('precision','16') 
Query time 0.008 
load_library('accelerated_io_tools') 
Query time 0.007 
load_library('dense_linear_algebra') 
Query time 0.006 
load_library('example_udos') 
Query time 0.006 
load_library('superfunpack') 
Query time 0.006 
load_library('linear_algebra') 
Query time 0.006 
load_library('cu') 
list('operators') 
Query time 0.062 
Data transfer time 0.003 
R parsing time 0.001 
> t1 = proc.time(); t = iquery("scan(tmp)", return=TRUE); proc.time()-t1;
join(show('filter(scan(tmp),true)','afl'), _explain_logical('filter(scan(tmp),true)','afl')) 
Query time 0.051 
Data transfer time 0.003 
R parsing time 0.001 
join(show('filter(unpack(scan(tmp), i),true)','afl'), _explain_logical('filter(unpack(scan(tmp), i),true)','afl')) 
Query time 0.053 
Data transfer time 0.003 
R parsing time 0.001 
unpack(scan(tmp), i) 
Query time 27.058 
Data transfer time 4.054 
  R buffer  1700000 / 3.4e+09  bytes parsing time 0.018 
  R rbind/df assembly time 0.004 
  R buffer  1701700000 / 3.4e+09  bytes parsing time 18.217 
  R rbind/df assembly time 1.571 
  R buffer  3.4e+09 / 3.4e+09  bytes parsing time 18.205 
  R rbind/df assembly time 3.893 
Total R parsing time 41.908 
   user  system elapsed 
 40.280   6.753  74.604 
> 3.2*1024/74.6
[1] 43.92493
```

But as they say, everything is different the second time around:
```R
> t1 = proc.time(); t = iquery("scan(tmp)", return=TRUE); proc.time()-t1;
join(show('filter(scan(tmp),true)','afl'), _explain_logical('filter(scan(tmp),true)','afl')) 
Query time 0.052 
Data transfer time 0.003 
R parsing time 0.001 
join(show('filter(unpack(scan(tmp), i),true)','afl'), _explain_logical('filter(unpack(scan(tmp), i),true)','afl')) 
Query time 0.054 
Data transfer time 0.003 
R parsing time 0.001 
unpack(scan(tmp), i) 
Query time 26.969 
Data transfer time 112.531 
  R buffer  1700000 / 3.4e+09  bytes parsing time 0.018 
  R rbind/df assembly time 0.003 
  R buffer  1701700000 / 3.4e+09  bytes parsing time 18.193 
  R rbind/df assembly time 1.552 
  R buffer  3.4e+09 / 3.4e+09  bytes parsing time 18.183 
  R rbind/df assembly time 3.895 
Total R parsing time 41.845 
   user  system elapsed 
 40.017 115.398 182.902 
> t1 = proc.time(); t = iquery("scan(tmp)", return=TRUE); proc.time()-t1;
join(show('filter(scan(tmp),true)','afl'), _explain_logical('filter(scan(tmp),true)','afl')) 
Query time 0.051 
Data transfer time 0.003 
R parsing time 0.001 
join(show('filter(unpack(scan(tmp), i),true)','afl'), _explain_logical('filter(unpack(scan(tmp), i),true)','afl')) 
Query time 0.055 
Data transfer time 0.003 
R parsing time 0.001 
unpack(scan(tmp), i) 
Query time 27.137 
Data transfer time 191.33 
  R buffer  1700000 / 3.4e+09  bytes parsing time 0.018 
  R rbind/df assembly time 0.003 
  R buffer  1701700000 / 3.4e+09  bytes parsing time 18.192 
  R rbind/df assembly time 1.527 
  R buffer  3.4e+09 / 3.4e+09  bytes parsing time 18.175 
  R rbind/df assembly time 3.871 
Total R parsing time 41.786 
   user  system elapsed 
 40.454 193.698 261.815 
> t1 = proc.time(); j = iquery("scan(tmp)", return=TRUE); proc.time()-t1;
join(show('filter(scan(tmp),true)','afl'), _explain_logical('filter(scan(tmp),true)','afl')) 
Query time 0.052 
Data transfer time 0.003 
R parsing time 0.001 
join(show('filter(unpack(scan(tmp), i),true)','afl'), _explain_logical('filter(unpack(scan(tmp), i),true)','afl')) 
Query time 0.057 
Data transfer time 0.003 
R parsing time 0.001 
unpack(scan(tmp), i) 
Query time 27.127 
Data transfer time 114.361 
  R buffer  1700000 / 3.4e+09  bytes parsing time 0.018 
  R rbind/df assembly time 0.002 
  R buffer  1701700000 / 3.4e+09  bytes parsing time 18.193 
  R rbind/df assembly time 1.527 
  R buffer  3.4e+09 / 3.4e+09  bytes parsing time 18.175 
  R rbind/df assembly time 3.883 
Total R parsing time 41.799 
   user  system elapsed 
 39.826 117.405 184.884 
```

**Comment by bwlewis** [comment]
Try it now, after this commit https://github.com/Paradigm4/SciDBR/commit/fffc1c6c49c590aa412eaee64246f91d01e5fbf4

I'm not 100% sure what was affecting the transfer rate in your examples, but I added some explicit garbage collection that seems to help.

There is still one extra copy of the data after the collection step that I can't garbage collect. Running gc() manually will free it. Of course under memory pressure the GC will run on its own more frequently.
