### ISSUE TITLE
Print information about arrays

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDBR#91]
I have SciDB `15.7` and installed SciDBR from `master`. Following the documentation, I do:
```
> x <- scidb("build(<v:double>[i=1:2,2,0, j=1:3,1,0], i*j)")
> print(x)
A reference to a  2x3 SciDB array
```
How can I get more information about `x` when I do `print(x)`? The [documentation](http://paradigm4.github.io/SciDBR/) shows:
```
> x <- scidb("build(<v:double>[i=1:2,2,0, j=1:3,1,0], i*j)")
> print(x)
SciDB expression  build(<v:double>[i=1:2,2,0, j=1:3,1...
SciDB schema  <v:double> [i=1:2,2,0,j=1:3,1,0] 
  variable dimension   type nullable start end chunk
1        i      TRUE  int64    FALSE     1   2     2
2        j      TRUE  int64    FALSE     1   3     1
3        v     FALSE double    FALSE                
```

**Comment by apoliakov** [comment]
Hey Rares,

Yeah I think right now the master is behind the doc. Try:
```R
remove.packages('scidb')
library(devtools)
install_github('paradigm4/SciDBR', ref='laboratory')
```
That should do it.

In the older version, there were other options like:
```R
x@schema
x@name
str(x)
```

**Comment by bwlewis** [comment]
Yes, now that the package tests are passing I'm going to update the
ancient master branch that is way out of date. Probably tonight.

x <- scidb("build(<v:double>[i=1:10,10,0], sin(i))")  # an example array object
schema(x)   # shows array schema
x@name     # shows the low-level scidb expression that generates x
x[ ]               # downloads data from x to R
