### ISSUE TITLE
Cannot use "Inf" in iqdf function

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDBR#95]
**Problem Description**

Doing the below:

res=iqdf(query,n=Inf)

Results in the below shortened error statement:

               ), Inf),true)','afl')) 
Error in value[[3L]](cond) : 
  Error in SGET("/execute_query", list(id = sessionid, release = release, : HTTP error 500
UserQueryException in file: src/query/parser/Translator.cpp function: matchOperatorParam line: 1408
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_WRONG_OPERATOR_ARGUMENT2
Error description: Query processor error. Parameter must be constant with type 'uint64'.
filter(limit(

**Other Info**

If I take the query that is generated by R, switch "Inf" for "inf" and pass it through iquery, this query runs correctly.

**Comment by apoliakov** [comment]
iqdf was created before when you could get either matrix or data.frame out of R. one of the reasons for iqdf is to force a data frame return (hence "df"). Maybe now that everything is df we can just remove it in favor of something like
```
iquery(query, return=TRUE, n=Inf)
```
just making sure that when n is not "Inf" and limit is available we can use limit appropriately.

**Comment by jrivers96** [comment]
The problem is the "n = Inf". I think scidb was changed to lower case, so
the conversion does not happen appropriately.

On Tue, Jun 7, 2016 at 1:10 PM, apoliakov <notifications@github.com> wrote:

> iqdf was created before when you could get either matrix or data.frame out
> of R. one of the reasons for iqdf is to force a data frame return (hence
> "df"). Maybe now that everything is df we can just remove it in favor of
> something like
>
> iquery(query, return=TRUE, n=Inf)
>
> just making sure that when n is not "Inf" and limit is available we can
> use limit appropriately.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Paradigm4/SciDBR/issues/95#issuecomment-224348526>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKhe9GnReFqKrjIEj2AzWYd45fM-2eaGks5qJaYDgaJpZM4IwEwb>
> .
>



-- 
Jonathan Rivers
Customer Solutions
Paradigm4
jrivers@paradigm4.com <erobinson@paradigm4.com>
Mobile: (646) 463-4890 <%28617%29%20780-1743>
www.paradigm4.com



<http://discover.paradigm4.com/paradigm4-gartner-cool-vendor-2016.html?utm_source=signature&utm_medium=email&utm_campaign=gartnercv>

**Comment by apoliakov** [comment]
??? inf is a keyword in scidb?
