### ISSUE TITLE
Subset error on bools

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDBR#99]
I noticed this error:
```R
> options(scidb.debug = FALSE)
> iquery("store(build(<val:bool>[i=0:1,2,0], iif(i%2 = 0, true, false)), temp_demo)")
> temp=scidb("temp_demo")
> subset(temp, val == TRUE)[]
Error in value[[3L]](cond) : 
  Error in SGET("/execute_query", list(id = sessionid, release = release, : HTTP error 500
UserQueryException in file: src/query/Expression.cpp function: internalCompile line: 567
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_FUNCTION_NOT_FOUND
Error description: Query processor error. Function '=(bool, double)' not found.
filter(filter(temp_demo,val = 1.0000000000000000),true)
                           ^^
> iquery("filter(temp_demo, val = TRUE)", return = TRUE)
  i  val
1 0 TRUE
> scidbrm("temp_demo", force=TRUE)
```
Seems that the value of TRUE is being replaced by 1.0000

**Comment by bwlewis** [comment]
Working on this.

Unrelated, but about format for posting issues. Here are a few guidelines:

1. Don't use the SciDB catalog unless you absolutely have to for reproduction of the error.
2. Use markdown when possible (the triple backtick r notation)

This makes the bug reports much easier to copy + paste repro. For instance, I would prefer the above bug to be written as:

```{r}
options(scidb.debug = FALSE)
temp=scidb("build(<val:bool>[i=0:1,2,0], iif(i%2 = 0, true, false))")
subset(temp, val == TRUE)[]
```

**Comment by ksens** [comment]
Good points. 

1. I see now how you avoid using the SciDB catalog. 
2. Actually I was using the triple tick notation, but I was also copying the extra `>` characters from RStudio and putting the errors inline. Will avoid those in the future.
